from __future__ import annotations

SKILL_ALIASES = {
    "javascript": "JavaScript",
    "js": "JavaScript",
    "typescript": "TypeScript",
    "ts": "TypeScript",
    "reactjs": "React",
    "react.js": "React",
    "node": "Node.js",
    "nodejs": "Node.js",
    "node.js": "Node.js",
    "express": "Express.js",
    "expressjs": "Express.js",
    "html5": "HTML",
    "css3": "CSS",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "mysql": "MySQL",
    "mongo": "MongoDB",
    "mongodb": "MongoDB",
    "rest": "REST API",
    "rest api": "REST API",
    "graphql": "GraphQL",
    "aws": "AWS",
    "machine learning": "Machine Learning",
    "ml": "Machine Learning",
    "data analysis": "Data Analysis",
    "powerbi": "Power BI",
    "power bi": "Power BI",
    "dsa": "DSA",
    "system design": "System Design",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "numpy": "NumPy",
    "pandas": "Pandas",
    "fast api": "FastAPI",
    "fastapi": "FastAPI",
    "classroom management": "Classroom Management",
    "lesson planning": "Lesson Planning",
    "curriculum design": "Curriculum Design",
}

EDUCATION_KEYWORDS = {
    "btech": "BTech",
    "b.e": "BE",
    "be ": "BE",
    "bachelor": "Bachelor",
    "mtech": "MTech",
    "master": "Master",
    "mba": "MBA",
    "mca": "MCA",
    "bca": "BCA",
    "diploma": "Diploma",
}

EXPERIENCE_KEYWORDS = (
    "intern",
    "developer",
    "engineer",
    "teacher",
    "assistant",
    "analyst",
    "worked",
    "experience",
    "freelance",
)

STOPWORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "by",
    "for",
    "from",
    "in",
    "into",
    "is",
    "it",
    "of",
    "on",
    "or",
    "the",
    "to",
    "with",
    "will",
    "your",
    "you",
}
